//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spa_Vehiculos_api.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;

    public partial class Cita
    {
        public int ID_Cita { get; set; }
        public string Estado { get; set; }
        public string Observaciones { get; set; }
        public Nullable<System.DateTime> Fecha_Hora { get; set; }
        public string Vehiculo { get; set; }
        public int Cliente { get; set; }
        public int Sede { get; set; }

        [JsonIgnore]
        public virtual Vehiculo_Cliente Vehiculo_Cliente { get; set; }
        [JsonIgnore]
        public virtual Sede Sede1 { get; set; }
    }
}
