//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spa_Vehiculos_api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CITA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CITA()
        {
            this.FACTURAs = new HashSet<FACTURA>();
        }
    
        public int id_cita { get; set; }
        public Nullable<int> id_cliente { get; set; }
        public Nullable<int> id_vehiculo { get; set; }
        public Nullable<int> id_sede { get; set; }
        public System.DateTime fecha_hora { get; set; }
        public string estado_cita { get; set; }
        public string notas { get; set; }
    
        public virtual CLIENTE CLIENTE { get; set; }
        public virtual SEDE SEDE { get; set; }
        public virtual VEHICULO_CLIENTE VEHICULO_CLIENTE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FACTURA> FACTURAs { get; set; }
    }
}
