//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spa_Vehiculos_api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cita
    {
        public int ID_Cita { get; set; }
        public string Estado { get; set; }
        public string Observaciones { get; set; }
        public Nullable<System.DateTime> Fecha_Hora { get; set; }
        public string Vehiculo { get; set; }
        public int Cliente { get; set; }
        public int Sede { get; set; }
    
        public virtual Vehiculo_Cliente Vehiculo_Cliente { get; set; }
        public virtual Sede Sede1 { get; set; }
    }
}
