//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spa_Vehiculos_api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detalle_Orden_Compra
    {
        public int Numero_Orden { get; set; }
        public int ID_DetCompra { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public decimal Impuesto { get; set; }
        public Nullable<decimal> Precio_Unitario { get; set; }
        public Nullable<decimal> Subtotal { get; set; }
    
        public virtual Orden_Compra Orden_Compra { get; set; }
    }
}
