//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spa_Vehiculos_api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detalle_Orden_Compra
    {
        public int Numero_Orden { get; set; }
        public int ID_DetCompra { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public decimal Impuesto { get; set; }
        public Nullable<decimal> Precio_Unitario { get; set; }
        public Nullable<decimal> Subtotal { get; set; }
    
        public virtual Orden_Compra Orden_Compra { get; set; }
    }
}
