//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spa_Vehiculos_api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETALLE_ORDEN_COMPRA
    {
        public int id_detalle_orden { get; set; }
        public Nullable<int> id_orden_compra { get; set; }
        public Nullable<int> id_producto { get; set; }
        public int cantidad { get; set; }
        public decimal precio_unitario { get; set; }
        public decimal subtotal { get; set; }
    
        public virtual ORDEN_COMPRA ORDEN_COMPRA { get; set; }
        public virtual PRODUCTO PRODUCTO { get; set; }
    }
}
