//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spa_Vehiculos_api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detalle_Factura_Servicio
    {
        public int ID_Servicio { get; set; }
        public int ID_DetServicio { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public Nullable<decimal> Subtotal { get; set; }
        public Nullable<decimal> Precio { get; set; }
        public int Factura { get; set; }
    
        public virtual Factura Factura1 { get; set; }
        public virtual Servicio Servicio { get; set; }
    }
}
