//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spa_Vehiculos_api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETALLE_FACTURA_SERVICIO
    {
        public int id_detalle_servicio { get; set; }
        public Nullable<int> id_factura { get; set; }
        public Nullable<int> id_servicio { get; set; }
        public int cantidad { get; set; }
        public decimal precio_unitario { get; set; }
        public decimal subtotal { get; set; }
    
        public virtual FACTURA FACTURA { get; set; }
        public virtual SERVICIO SERVICIO { get; set; }
    }
}
