//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spa_Vehiculos_api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detalle_Factura_Servicio
    {
        public int ID_Servicio { get; set; }
        public int ID_DetServicio { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public Nullable<decimal> Subtotal { get; set; }
        public Nullable<decimal> Precio { get; set; }
        public int Factura { get; set; }
    
        public virtual Factura Factura1 { get; set; }
        public virtual Servicio Servicio { get; set; }
    }
}
