//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spa_Vehiculos_api.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class Empleado
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Empleado()
        {
            this.Perfils = new HashSet<Perfil>();
        }
    
        public int ID_Empleado { get; set; }
        public string Nombres { get; set; }
        public string Apellidos { get; set; }
        public Nullable<decimal> Salario { get; set; }
        public Nullable<System.DateTime> Fecha_Nacimiento { get; set; }
        public string Cargo { get; set; }
        public int Telefono { get; set; }
        public int Email { get; set; }
        public int Sede { get; set; }
    
        public virtual Email_Empleado Email_Empleado { get; set; }
        public virtual Sede Sede1 { get; set; }
        public virtual Telefono_Empleado Telefono_Empleado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]
        public virtual ICollection<Perfil> Perfils { get; set; }
    }
}
