//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spa_Vehiculos_api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleado
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Empleado()
        {
            this.Perfils = new HashSet<Perfil>();
        }
    
        public int ID_Empleado { get; set; }
        public string Nombres { get; set; }
        public string Apellidos { get; set; }
        public Nullable<decimal> Salario { get; set; }
        public Nullable<System.DateTime> Fecha_Nacimiento { get; set; }
        public string Cargo { get; set; }
        public int Telefono { get; set; }
        public int Email { get; set; }
        public int Sede { get; set; }
    
        public virtual Email_Empleado Email_Empleado { get; set; }
        public virtual Sede Sede1 { get; set; }
        public virtual Telefono_Empleado Telefono_Empleado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Perfil> Perfils { get; set; }
    }
}
