//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spa_Vehiculos_api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FACTURA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FACTURA()
        {
            this.DETALLE_FACTURA_PRODUCTO = new HashSet<DETALLE_FACTURA_PRODUCTO>();
            this.DETALLE_FACTURA_SERVICIO = new HashSet<DETALLE_FACTURA_SERVICIO>();
        }
    
        public int id_factura { get; set; }
        public Nullable<int> id_cita { get; set; }
        public Nullable<int> id_cliente { get; set; }
        public Nullable<int> id_sede { get; set; }
        public Nullable<int> id_empleado { get; set; }
        public string numero_factura { get; set; }
        public System.DateTime fecha_emision { get; set; }
        public decimal subtotal { get; set; }
        public decimal impuesto { get; set; }
        public Nullable<decimal> descuento { get; set; }
        public decimal total { get; set; }
        public string metodo_pago { get; set; }
        public string estado_pago { get; set; }
    
        public virtual CITA CITA { get; set; }
        public virtual CLIENTE CLIENTE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DETALLE_FACTURA_PRODUCTO> DETALLE_FACTURA_PRODUCTO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DETALLE_FACTURA_SERVICIO> DETALLE_FACTURA_SERVICIO { get; set; }
        public virtual EMPLEADO EMPLEADO { get; set; }
        public virtual SEDE SEDE { get; set; }
    }
}
