//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spa_Vehiculos_api.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class Factura
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Factura()
        {
            this.Detalle_Factura_Producto = new HashSet<Detalle_Factura_Producto>();
            this.Detalle_Factura_Servicio = new HashSet<Detalle_Factura_Servicio>();
        }
    
        public int ID_Factura { get; set; }
        public System.DateTime Fecha_Emision { get; set; }
        public string Estado_Pago { get; set; }
        public decimal Impuesto { get; set; }
        public Nullable<decimal> Descuento { get; set; }
        public Nullable<decimal> Total { get; set; }
        public int Sede { get; set; }
        public int Cliente { get; set; }
        public int Metodo_Pago { get; set; }
    
        public virtual Cliente Cliente1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]
        public virtual ICollection<Detalle_Factura_Producto> Detalle_Factura_Producto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]
        public virtual ICollection<Detalle_Factura_Servicio> Detalle_Factura_Servicio { get; set; }
        public virtual Metodo_Pago Metodo_Pago1 { get; set; }
        public virtual Sede Sede1 { get; set; }
    }
}
