//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spa_Vehiculos_api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class INVENTARIO_SEDE
    {
        public int id_inventario { get; set; }
        public Nullable<int> id_producto { get; set; }
        public Nullable<int> id_sede { get; set; }
        public int cantidad_actual { get; set; }
        public Nullable<int> punto_reorden { get; set; }
        public string ubicacion_almacen { get; set; }
    
        public virtual PRODUCTO PRODUCTO { get; set; }
        public virtual SEDE SEDE { get; set; }
    }
}
