//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spa_Vehiculos_api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDEN_COMPRA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ORDEN_COMPRA()
        {
            this.DETALLE_ORDEN_COMPRA = new HashSet<DETALLE_ORDEN_COMPRA>();
        }
    
        public int id_orden_compra { get; set; }
        public Nullable<int> id_proveedor { get; set; }
        public Nullable<int> id_sede { get; set; }
        public Nullable<int> id_empleado { get; set; }
        public string numero_orden { get; set; }
        public System.DateTime fecha_orden { get; set; }
        public Nullable<System.DateTime> fecha_entrega_esperada { get; set; }
        public string estado_orden { get; set; }
        public decimal subtotal { get; set; }
        public decimal impuesto { get; set; }
        public decimal total { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DETALLE_ORDEN_COMPRA> DETALLE_ORDEN_COMPRA { get; set; }
        public virtual EMPLEADO EMPLEADO { get; set; }
        public virtual PROVEEDOR PROVEEDOR { get; set; }
        public virtual SEDE SEDE { get; set; }
    }
}
