//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spa_Vehiculos_api.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class Orden_Compra
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Orden_Compra()
        {
            this.Detalle_Orden_Compra = new HashSet<Detalle_Orden_Compra>();
        }
    
        public int Numero_Orden { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<System.DateTime> Fecha_Entrega { get; set; }
        public string Estado { get; set; }
        public Nullable<decimal> Total { get; set; }
        public int Sede { get; set; }
        public int Proveedor { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]
        public virtual ICollection<Detalle_Orden_Compra> Detalle_Orden_Compra { get; set; }
        public virtual Proveedor Proveedor1 { get; set; }
        public virtual Sede Sede1 { get; set; }
    }
}
