//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spa_Vehiculos_api.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;

    public partial class Perfil
    {
        public int ID_Empleado { get; set; }
        public int ID_Perfil { get; set; }
        public string Usuario { get; set; }
        public string Clave { get; set; }

        [JsonIgnore]
        public virtual Empleado Empleado { get; set; }
    }
}
