//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spa_Vehiculos_api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Perfil
    {
        public int ID_Empleado { get; set; }
        public int ID_Perfil { get; set; }
        public string Usuario { get; set; }
        public string Clave { get; set; }
    
        public virtual Empleado Empleado { get; set; }
    }
}
