//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spa_Vehiculos_api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRECIO_SERVICIO
    {
        public int id_precio_servicio { get; set; }
        public Nullable<int> id_servicio { get; set; }
        public Nullable<int> id_sede { get; set; }
        public decimal precio { get; set; }
        public System.DateTime fecha_inicio_vigencia { get; set; }
        public Nullable<System.DateTime> fecha_fin_vigencia { get; set; }
    
        public virtual SERVICIO SERVICIO { get; set; }
        public virtual SEDE SEDE { get; set; }
    }
}
