//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spa_Vehiculos_api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCTO_PROVEEDOR
    {
        public int id_producto_proveedor { get; set; }
        public Nullable<int> id_producto { get; set; }
        public Nullable<int> id_proveedor { get; set; }
        public Nullable<decimal> precio_compra { get; set; }
        public Nullable<int> tiempo_entrega { get; set; }
        public Nullable<int> cantidad_minima { get; set; }
        public Nullable<bool> es_proveedor_principal { get; set; }
    
        public virtual PRODUCTO PRODUCTO { get; set; }
        public virtual PROVEEDOR PROVEEDOR { get; set; }
    }
}
