//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spa_Vehiculos_api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SERVICIO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SERVICIO()
        {
            this.DETALLE_FACTURA_SERVICIO = new HashSet<DETALLE_FACTURA_SERVICIO>();
            this.PRECIO_SERVICIO = new HashSet<PRECIO_SERVICIO>();
        }
    
        public int id_servicio { get; set; }
        public Nullable<int> id_categoria_servicio { get; set; }
        public string nombre_servicio { get; set; }
        public string descripcion { get; set; }
        public Nullable<int> duracion_estimada { get; set; }
    
        public virtual CATEGORIA_SERVICIO CATEGORIA_SERVICIO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DETALLE_FACTURA_SERVICIO> DETALLE_FACTURA_SERVICIO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRECIO_SERVICIO> PRECIO_SERVICIO { get; set; }
    }
}
