//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spa_Vehiculos_api.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SpaVehicularEntities : DbContext
    {
        public SpaVehicularEntities()
            : base("name=SpaVehicularEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Categoria_Producto> Categoria_Producto { get; set; }
        public virtual DbSet<Categoria_Servicio> Categoria_Servicio { get; set; }
        public virtual DbSet<Cita> Citas { get; set; }
        public virtual DbSet<Ciudad> Ciudads { get; set; }
        public virtual DbSet<Cliente> Clientes { get; set; }
        public virtual DbSet<Departamento> Departamentoes { get; set; }
        public virtual DbSet<Detalle_Factura_Producto> Detalle_Factura_Producto { get; set; }
        public virtual DbSet<Detalle_Factura_Servicio> Detalle_Factura_Servicio { get; set; }
        public virtual DbSet<Detalle_Orden_Compra> Detalle_Orden_Compra { get; set; }
        public virtual DbSet<Direccion_Cliente> Direccion_Cliente { get; set; }
        public virtual DbSet<Email_Cliente> Email_Cliente { get; set; }
        public virtual DbSet<Email_Empleado> Email_Empleado { get; set; }
        public virtual DbSet<Empleado> Empleadoes { get; set; }
        public virtual DbSet<Factura> Facturas { get; set; }
        public virtual DbSet<Metodo_Pago> Metodo_Pago { get; set; }
        public virtual DbSet<Orden_Compra> Orden_Compra { get; set; }
        public virtual DbSet<Perfil> Perfils { get; set; }
        public virtual DbSet<Producto> Productoes { get; set; }
        public virtual DbSet<Producto_Proveedor> Producto_Proveedor { get; set; }
        public virtual DbSet<Proveedor> Proveedors { get; set; }
        public virtual DbSet<Sede> Sedes { get; set; }
        public virtual DbSet<Servicio> Servicios { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Telefono_Cliente> Telefono_Cliente { get; set; }
        public virtual DbSet<Telefono_Empleado> Telefono_Empleado { get; set; }
        public virtual DbSet<Vehiculo_Cliente> Vehiculo_Cliente { get; set; }
    }
}
